# Prettier Configuration for Level Up Community Commands

# Basic formatting
semi: true
singleQuote: true
tabWidth: 2
useTabs: false
trailingComma: 'none'

# Line length
printWidth: 100

# Brackets and spacing
bracketSpacing: true
bracketSameLine: false
arrowParens: 'avoid'

# JavaScript specific
quoteProps: 'as-needed'

# File types
overrides:
  - files: '*.json'
    options:
      parser: 'json'
      tabWidth: 2

  - files: '*.md'
    options:
      parser: 'markdown'
      proseWrap: 'preserve'
      tabWidth: 2

  - files: '*.yml'
    options:
      parser: 'yaml'
      tabWidth: 2
