name: 🐛 Bug Report
description: Report a bug with an existing community command
title: '[BUG] '
labels: ['bug', 'needs-triage']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! This helps us improve the quality of community commands.

  - type: input
    id: command-name
    attributes:
      label: Command Name
      description: Which command is experiencing the bug?
      placeholder: 'e.g., Export View to Excel'
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: What is the bug? What did you expect to happen vs. what actually happened?
      placeholder: 'A clear and concise description of what the bug is...'
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Execute command '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your Dynamics 365 environment details
      placeholder: |
        - Dynamics 365 Version: [e.g., Online, v9.2]
        - Browser: [e.g., Chrome 96.0]
        - Level Up Extension Version: [e.g., 2.1.0]
        - Entity/Form: [e.g., Contact form]
    validations:
      required: true

  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages
      description: Any error messages or console output
      placeholder: 'Paste any error messages here...'
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: 'Add any other context or screenshots about the bug here...'
